default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: cli-check
        name: CLI checks
        entry: make cli-check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
      - id: cli-integration-test
        name: CLI integration tests
        entry: make cli-integration-test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
