// Code generated by scopedrepo-gen; DO NOT EDIT.
package scopedrepo

const (
	query_alias       = "INSERT INTO scope_aliases(scope_id,kind,alias,resource_id) VALUES(?,?,?,?)\n"
	query_directory   = "SELECT scope_id FROM scope_memberships\nWHERE principal=? AND scope_id>? ORDER BY scope_id LIMIT ?\n"
	query_domain      = "SELECT state FROM scope_domains WHERE id=?\n"
	query_identity    = "SELECT r.scope_id,r.kind,r.id,k.rid,r.canonical_id,r.version\nFROM scope_resources r JOIN scope_resource_rids k\n ON k.scope_id=r.scope_id AND k.kind=r.kind AND k.resource_id=r.id\nWHERE r.scope_id=? AND r.kind=? AND r.id=?\n"
	query_projection  = "INSERT INTO scope_projection_values(scope_id,projection_key,value) VALUES(?,?,?)\nON CONFLICT(scope_id,projection_key) DO UPDATE SET value=excluded.value\n"
	query_register    = "INSERT INTO scope_resources(scope_id,kind,id,canonical_id,version) VALUES(?,?,?,?,1)\n"
	query_replay      = "SELECT scope_id,kind,request_hash,resource_id FROM scope_replays\nWHERE principal=? AND replay_key=?\n"
	query_role        = "SELECT d.state,m.role FROM scope_memberships m\nJOIN scope_domains d ON d.id=m.scope_id\nWHERE m.principal=? AND m.scope_id=?\n"
	query_save_replay = "INSERT INTO scope_replays(principal,replay_key,scope_id,kind,request_hash,resource_id) VALUES(?,?,?,?,?,?)\n"
	query_title       = "SELECT CASE WHEN length(CAST(COALESCE(d.title,'') AS BLOB))<=65536 THEN COALESCE(d.title,'') END FROM scope_resources r\nJOIN documents d ON d.id=r.canonical_id\nWHERE r.scope_id=? AND r.kind='doc' AND r.id=?\n"
)
