// Code generated by scopedrepo-gen; DO NOT EDIT.
package scopedrepo

const (
	query_alias               = "INSERT INTO scope_aliases(scope_id,kind,alias,resource_id) VALUES(?,?,?,?)\n"
	query_directory           = "SELECT scope_id FROM scope_memberships\nWHERE principal=? AND scope_id>? ORDER BY scope_id LIMIT ?\n"
	query_domain              = "SELECT state FROM scope_domains WHERE id=?\n"
	query_feed_after          = "SELECT sort_key,rid,version FROM scope_feed\n WHERE scope_id=? AND generation=? AND family=? AND audience_key=?\n AND (sort_key,rid)>(?,?) ORDER BY sort_key,rid LIMIT ?\n"
	query_feed_authority      = "SELECT d.state,d.generation,m.role,m.generation\n FROM scope_memberships m JOIN scope_domains d ON d.id=m.scope_id\n WHERE m.principal=? AND m.scope_id=?\n"
	query_feed_binding        = "SELECT membership_generation,binding_generation FROM scope_feed_bindings\n WHERE principal=? AND scope_id=? AND generation=? AND family=? AND audience_key=?\n"
	query_feed_buckets_suffix = ") SELECT q.bucket,c.value FROM requested q\n LEFT JOIN scope_counters c ON c.scope_id=q.scope_id AND c.generation=q.generation\n AND c.family=q.family AND c.audience_key=q.audience_key AND c.bucket=q.bucket\n"
	query_feed_generation     = "SELECT projection_version,audience_version,lifecycle_version,legacy_auth_version,legacy_auth_epoch\n FROM scope_feed_generations WHERE scope_id=? AND generation=?\n"
	query_feed_hydrate_suffix = ")\n SELECT q.ord,CASE WHEN length(CAST(k.kind AS BLOB))<=32 THEN k.kind END,\n CASE WHEN length(CAST(k.resource_id AS BLOB))<=479 THEN k.resource_id END,\n CASE WHEN length(CAST(p.data AS BLOB))<=16384 THEN p.data END,r.version\n FROM requested q\n LEFT JOIN scope_feed f ON f.scope_id=q.scope_id AND f.generation=q.generation\n AND f.family=q.family AND f.audience_key=q.audience_key AND f.sort_key=q.sort_key AND f.rid=q.rid AND f.version=q.version\n LEFT JOIN scope_feed_payloads p ON p.scope_id=f.scope_id AND p.generation=f.generation\n AND p.family=f.family AND p.audience_key=f.audience_key AND p.rid=f.rid AND p.version=f.version\n LEFT JOIN scope_resource_rids k ON k.rid=p.rid AND k.scope_id=p.scope_id\n LEFT JOIN scope_resources r ON r.scope_id=k.scope_id AND r.kind=k.kind AND r.id=k.resource_id AND r.version=q.version\n"
	query_feed_legacy_epoch   = "SELECT version FROM resource_access_epoch WHERE singleton=1\n"
	query_feed_start          = "SELECT sort_key,rid,version FROM scope_feed\n WHERE scope_id=? AND generation=? AND family=? AND audience_key=?\n ORDER BY sort_key,rid LIMIT ?\n"
	query_identity            = "SELECT r.scope_id,r.kind,r.id,k.rid,r.canonical_id,r.version\nFROM scope_resources r JOIN scope_resource_rids k\n ON k.scope_id=r.scope_id AND k.kind=r.kind AND k.resource_id=r.id\nWHERE r.scope_id=? AND r.kind=? AND r.id=?\n"
	query_legacy_identity     = "SELECT\n CASE WHEN typeof(r.scope_id)='text' AND length(CAST(r.scope_id AS BLOB)) BETWEEN 1 AND 256 THEN r.scope_id END,\n CASE WHEN typeof(r.id)='text' AND length(CAST(r.id AS BLOB)) BETWEEN 1 AND 32 THEN r.id END,\n CASE WHEN typeof(r.version)='integer' AND r.version>0 THEN r.version END,\n k.rid\nFROM scope_resources r LEFT JOIN scope_resource_rids k\n ON k.scope_id=r.scope_id AND k.kind=r.kind AND k.resource_id=r.id\nWHERE r.kind=? AND r.canonical_id=?\n"
	query_legacy_register     = "INSERT INTO scope_resources(scope_id,kind,id,canonical_id,version) VALUES(?,?,?,?,?)\n"
	query_legacy_sink         = "SELECT 1 FROM scope_domains d\nWHERE d.id=? AND d.state='inaccessible'\n AND NOT EXISTS(SELECT 1 FROM scope_memberships m WHERE m.scope_id=d.id)\n"
	query_projection          = "INSERT INTO scope_projection_values(scope_id,projection_key,value) VALUES(?,?,?)\nON CONFLICT(scope_id,projection_key) DO UPDATE SET value=excluded.value\n"
	query_register            = "INSERT INTO scope_resources(scope_id,kind,id,canonical_id,version) VALUES(?,?,?,?,1)\n"
	query_replay              = "SELECT scope_id,kind,request_hash,resource_id FROM scope_replays\nWHERE principal=? AND replay_key=?\n"
	query_role                = "SELECT d.state,m.role FROM scope_memberships m\nJOIN scope_domains d ON d.id=m.scope_id\nWHERE m.principal=? AND m.scope_id=?\n"
	query_save_replay         = "INSERT INTO scope_replays(principal,replay_key,scope_id,kind,request_hash,resource_id) VALUES(?,?,?,?,?,?)\n"
	query_title               = "SELECT CASE WHEN length(CAST(COALESCE(d.title,'') AS BLOB))<=65536 THEN COALESCE(d.title,'') END FROM scope_resources r\nJOIN documents d ON d.id=r.canonical_id\nWHERE r.scope_id=? AND r.kind='doc' AND r.id=?\n"
)
