// Code generated by scripts/sync-version.sh; DO NOT EDIT.

package buildinfo

var Current = "v0.12.45"

// SourceRevision is populated by release builds or Go's embedded VCS metadata.
var SourceRevision = "unknown"
