// scopedrepo-gen copies reviewed SQL templates into Go constants. The manifest
// records ownership; it does not interpret policy or generate arbitrary queries.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func generate(root string) ([]byte, error) {
	b, e := os.ReadFile(filepath.Join(root, "manifest.json"))
	if e != nil {
		return nil, e
	}
	var manifest map[string]string
	if e = json.Unmarshal(b, &manifest); e != nil {
		return nil, e
	}
	names := make([]string, 0, len(manifest))
	for name, owner := range manifest {
		if name == "" || strings.Trim(name, "abcdefghijklmnopqrstuvwxyz_") != "" {
			return nil, fmt.Errorf("invalid template name %q", name)
		}
		if owner != "scope" && owner != "principal" && owner != "authority" {
			return nil, fmt.Errorf("unreviewed ownership %q", owner)
		}
		names = append(names, name)
	}
	sort.Strings(names)
	files, e := filepath.Glob(filepath.Join(root, "queries", "*.sql"))
	if e != nil {
		return nil, e
	}
	if len(files) != len(names) {
		return nil, fmt.Errorf("template/manifest coverage mismatch")
	}
	var out strings.Builder
	out.WriteString("// Code generated by scopedrepo-gen; DO NOT EDIT.\npackage scopedrepo\n\nconst (\n")
	for _, name := range names {
		sql, e := os.ReadFile(filepath.Join(root, "queries", name+".sql"))
		if e != nil {
			return nil, e
		}
		fmt.Fprintf(&out, "query_%s = %s\n", name, strconv.Quote(string(sql)))
	}
	out.WriteString(")\n")
	return format.Source([]byte(out.String()))
}
func main() {
	root := flag.String("root", ".", "reviewed repository directory")
	check := flag.Bool("check", false, "verify generated file without writes")
	flag.Parse()
	b, e := generate(*root)
	if e == nil {
		path := filepath.Join(*root, "queries_gen.go")
		if *check {
			var old []byte
			old, e = os.ReadFile(path)
			if e == nil && string(old) != string(b) {
				e = fmt.Errorf("generated templates are stale")
			}
		} else {
			e = os.WriteFile(path, b, 0644)
		}
	}
	if e != nil {
		fmt.Fprintln(os.Stderr, e)
		os.Exit(1)
	}
}
