/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,svelte}"],
  theme: {
    colors: {
      bg: "var(--bg)",
      "bg-soft": "var(--bg-soft)",
      panel: "var(--panel)",
      "panel-hover": "var(--panel-hover)",
      line: "var(--line)",
      "line-subtle": "var(--line-subtle)",
      "line-strong": "var(--line-strong)",
      fg: "var(--fg)",
      "fg-muted": "var(--fg-muted)",
      "fg-subtle": "var(--fg-subtle)",
      accent: "var(--accent)",
      "accent-hover": "var(--accent-hover)",
      "accent-text": "var(--accent-text)",
      "accent-soft": "var(--accent-soft)",
      danger: "var(--danger)",
      "danger-text": "var(--danger-text)",
      "danger-soft": "var(--danger-soft)",
      warn: "var(--warn)",
      "warn-text": "var(--warn-text)",
      "warn-soft": "var(--warn-soft)",
      ok: "var(--ok)",
      "ok-text": "var(--ok-text)",
      "ok-soft": "var(--ok-soft)",
      info: "var(--info)",
      transparent: "transparent",
      current: "currentColor",
      white: "#fff",
      black: "#000",
    },
    fontSize: {
      micro: ["12px", { lineHeight: "1.3", fontWeight: "500" }],
      meta: ["13px", { lineHeight: "1.4" }],
      mono: ["14px", { lineHeight: "1.4" }],
      body: ["15px", { lineHeight: "1.5" }],
      subtitle: ["17px", { lineHeight: "1.35", fontWeight: "600" }],
      title: ["20px", { lineHeight: "1.3", fontWeight: "600" }],
      display: ["28px", { lineHeight: "1.25", fontWeight: "600" }],
    },
    borderRadius: {
      sm: "4px",
      DEFAULT: "6px",
      md: "8px",
      lg: "10px",
      full: "9999px",
    },
  },
  plugins: [],
};
