#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Sync generated version metadata from the repo VERSION file.

Usage:
  ./scripts/sync-version.sh
  ./scripts/sync-version.sh --check
EOF
}

MODE="${1:-write}"
case "${MODE}" in
  write|--write)
    MODE="write"
    ;;
  --check)
    MODE="check"
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VERSION="$("${SCRIPT_DIR}/read-version.sh")"
TARGET="${REPO_ROOT}/cli/internal/buildinfo/version_generated.go"
TMP_FILE="$(mktemp)"
trap 'rm -f "${TMP_FILE}"' EXIT

cat > "${TMP_FILE}" <<EOF
// Code generated by scripts/sync-version.sh; DO NOT EDIT.

package buildinfo

var Current = "${VERSION}"
EOF

if [[ "${MODE}" == "check" ]]; then
  if ! cmp -s "${TMP_FILE}" "${TARGET}"; then
    echo "generated version metadata is out of date; run ./scripts/sync-version.sh" >&2
    exit 1
  fi
  exit 0
fi

mv "${TMP_FILE}" "${TARGET}"
