#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Sync generated version metadata from the repo VERSION file.

Usage:
  ./scripts/sync-version.sh
  ./scripts/sync-version.sh --check
EOF
}

MODE="${1:-write}"
case "${MODE}" in
  write|--write)
    MODE="write"
    ;;
  --check)
    MODE="check"
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VERSION="$("${SCRIPT_DIR}/read-version.sh")"
WEB_VERSION="${VERSION#v}"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

sync_target() {
  local target="$1"
  local tmp_file="$2"

  if [[ "${MODE}" == "check" ]]; then
    if ! cmp -s "${tmp_file}" "${target}"; then
      echo "generated version metadata is out of date; run ./scripts/sync-version.sh" >&2
      exit 1
    fi
    return 0
  fi

  mkdir -p "$(dirname "${target}")"
  mv "${tmp_file}" "${target}"
}

CLI_TARGET="${REPO_ROOT}/cli/internal/buildinfo/version_generated.go"
CLI_TMP="${TMP_DIR}/cli-version_generated.go"
cat > "${CLI_TMP}" <<EOF
// Code generated by scripts/sync-version.sh; DO NOT EDIT.

package buildinfo

var Current = "${VERSION}"
EOF
sync_target "${CLI_TARGET}" "${CLI_TMP}"

CORE_TARGET="${REPO_ROOT}/core/internal/buildinfo/version_generated.go"
CORE_TMP="${TMP_DIR}/core-version_generated.go"
cat > "${CORE_TMP}" <<EOF
// Code generated by scripts/sync-version.sh; DO NOT EDIT.

package buildinfo

var Current = "${VERSION}"
EOF
sync_target "${CORE_TARGET}" "${CORE_TMP}"

WEB_GENERATED_TARGET="${REPO_ROOT}/web-ui/src/lib/generated/version.js"
WEB_GENERATED_TMP="${TMP_DIR}/web-version.js"
cat > "${WEB_GENERATED_TMP}" <<EOF
// Code generated by scripts/sync-version.sh; DO NOT EDIT.

export const CURRENT_VERSION = "${VERSION}";
EOF
sync_target "${WEB_GENERATED_TARGET}" "${WEB_GENERATED_TMP}"

WEB_PACKAGE_TARGET="${REPO_ROOT}/web-ui/package.json"
WEB_PACKAGE_TMP="${TMP_DIR}/web-package.json"
perl -0pe 's/"version":\s*"[^"]+"/"version": "'"${WEB_VERSION}"'"/' "${WEB_PACKAGE_TARGET}" > "${WEB_PACKAGE_TMP}"
sync_target "${WEB_PACKAGE_TARGET}" "${WEB_PACKAGE_TMP}"
